#!/usr/bin/env node

import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';

dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_ANON_KEY;

console.log('🔧 Teste rápido de configuração');
console.log('==============================');

console.log('📋 Variáveis de ambiente:');
console.log('SUPABASE_URL:', supabaseUrl ? '✅ Configurada' : '❌ Não configurada');
console.log('SUPABASE_ANON_KEY:', supabaseKey ? '✅ Configurada' : '❌ Não configurada');

if (!supabaseUrl || !supabaseKey) {
  console.error('\n❌ Configure as variáveis no arquivo .env');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

async function testConnection() {
  try {
    console.log('\n🔄 Testando conexão...');
    
    // Teste simples
    const { data, error } = await supabase
      .from('tarefas')
      .select('id')
      .limit(1);
    
    if (error) {
      if (error.code === 'PGRST116') {
        console.log('⚠️ Tabela "tarefas" não existe');
        console.log('📋 Execute o SQL no Supabase:');
        console.log('https://nexmkcseutopfnbazstb.supabase.co/project/sql');
        console.log('\nSQL para executar:');
        console.log(`CREATE TABLE IF NOT EXISTS tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'em_andamento', 'concluida')),
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE tarefas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all operations on tarefas" ON tarefas FOR ALL USING (true) WITH CHECK (true);`);
      } else {
        console.error('❌ Erro:', error.message);
      }
    } else {
      console.log('✅ Conexão OK!');
      console.log(`📊 ${data.length} tarefa(s) encontrada(s)`);
    }
    
  } catch (err) {
    console.error('❌ Erro:', err.message);
  }
}

testConnection();
