#!/usr/bin/env node

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://nexmkcseutopfnbazstb.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5leG1rY3NldXRvcGZuYmF6c3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MzU2NzAsImV4cCI6MjA4NTMxMTY3MH0.pzVcZHFJuIv9ndOszvPMxAPJQAdWfnwpBioR5VCYftY';

const supabase = createClient(supabaseUrl, supabaseKey);

async function testConnection() {
  console.log('🔄 Testando conexão com Supabase...');
  
  try {
    // Teste simples - verificar se consegue acessar a API
    const { data, error } = await supabase
      .from('tarefas')
      .select('*')
      .limit(1);
    
    if (error) {
      console.error('❌ Erro:', error.message);
      console.log('\n💡 A tabela "tarefas" ainda não existe.');
      console.log('Vamos criá-la agora...');
      
      // Criar tabela manualmente
      await createTable();
    } else {
      console.log('✅ Conexão bem-sucedida!');
      console.log('📊 Tabela "tarefas" encontrada');
      console.log(`📝 ${data.length} tarefa(s) encontrada(s)`);
    }
  } catch (err) {
    console.error('❌ Erro de conexão:', err.message);
  }
}

async function createTable() {
  console.log('\n🔧 Criando tabela "tarefas"...');
  
  // SQL para criar tabela
  const createTableSQL = `
    CREATE TABLE IF NOT EXISTS tarefas (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        titulo VARCHAR(255) NOT NULL,
        descricao TEXT,
        status VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'em_andamento', 'concluida')),
        criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
        atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
    );
    
    CREATE INDEX IF NOT EXISTS idx_tarefas_status ON tarefas(status);
    CREATE INDEX IF NOT EXISTS idx_tarefas_criado_em ON tarefas(criado_em DESC);
    
    ALTER TABLE tarefas ENABLE ROW LEVEL SECURITY;
    
    CREATE POLICY "Allow all operations on tarefas" ON tarefas
        FOR ALL USING (true) WITH CHECK (true);
  `;
  
  try {
    // Tentar criar tabela via RPC (se disponível)
    const { error } = await supabase.rpc('exec_sql', { sql: createTableSQL });
    
    if (error) {
      console.log('⚠️ Não foi possível criar tabela via script');
      console.log('📋 Por favor, execute manualmente no SQL Editor do Supabase:');
      console.log('\n' + createTableSQL);
      console.log('\n🔗 Acesse: https://nexmkcseutopfnbazstb.supabase.co/project/sql');
    } else {
      console.log('✅ Tabela criada com sucesso!');
      
      // Inserir dados de teste
      await insertTestData();
    }
  } catch (err) {
    console.log('⚠️ Erro ao criar tabela:', err.message);
    console.log('📋 Execute o SQL manualmente no painel Supabase');
  }
}

async function insertTestData() {
  console.log('\n🧪 Inserindo dados de teste...');
  
  const testData = [
    { titulo: 'Exemplo de tarefa', descricao: 'Esta é uma tarefa de exemplo', status: 'pendente' },
    { titulo: 'Tarefa em andamento', descricao: 'Trabalhando nesta tarefa', status: 'em_andamento' },
    { titulo: 'Tarefa concluída', descricao: 'Tarefa finalizada com sucesso', status: 'concluida' }
  ];
  
  try {
    const { data, error } = await supabase
      .from('tarefas')
      .insert(testData)
      .select();
    
    if (error) {
      console.error('❌ Erro ao inserir dados:', error.message);
    } else {
      console.log('✅ Dados inseridos com sucesso!');
      console.log(`📊 ${data.length} tarefas criadas`);
    }
  } catch (err) {
    console.error('❌ Erro:', err.message);
  }
}

// Executar teste
testConnection();
