-- Schema para tabela de tarefas no Supabase
-- Execute este SQL no painel SQL do seu projeto Supabase

-- Criar tabela de tarefas
CREATE TABLE IF NOT EXISTS tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descricao TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'em_andamento', 'concluida')),
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    atualizado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Criar índices para melhor performance
CREATE INDEX IF NOT EXISTS idx_tarefas_status ON tarefas(status);
CREATE INDEX IF NOT EXISTS idx_tarefas_criado_em ON tarefas(criado_em DESC);

-- Criar trigger para atualizar o campo atualizado_em automaticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.atualizado_em = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_tarefas_updated_at 
    BEFORE UPDATE ON tarefas 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Habilitar Row Level Security (RLS) para maior segurança
ALTER TABLE tarefas ENABLE ROW LEVEL SECURITY;

-- Política para permitir todas as operações (ajuste conforme necessário)
CREATE POLICY "Allow all operations on tarefas" ON tarefas
    FOR ALL USING (true) WITH CHECK (true);

-- Inserir dados de exemplo (opcional)
INSERT INTO tarefas (titulo, descricao, status) VALUES
    ('Exemplo de tarefa', 'Esta é uma tarefa de exemplo para testar o sistema', 'pendente'),
    ('Outra tarefa', 'Mais uma tarefa para demonstração', 'em_andamento'),
    ('Tarefa concluída', 'Uma tarefa que já foi finalizada', 'concluida')
ON CONFLICT DO NOTHING;
